
CACHE: False

NUM_SETS: 3

CROSS_VAL_ITERS: 5
#####
# Powers
#####
COMBINED_DEGREES: [3, 3, 0]
SIMPLE_DEGREES: [5, 11, 10]
TAN_HYP_DEGREES: [2,5,2]
INVERSE_LOG_DEGREES: [0,4,0]
ROOT_DEGREES: [0,4,0]
#########
# File paths
#########
DATA_TRAIN_PATH: '../data/train.csv'
DATA_TEST_PATH: '../data/test.csv'
OUTPUT_PATH: '../predictions.csv'

######
# Hyperparameters
######
lambdas: [1.321e-10,1.321e-10,1.321e-10]
# max_iters: [1000000,1000000,100000]
# gammas: [1e-1,1e-2,1e-2]
# logistics: [False,False,False]
# reg_fs:  [r,r,r]

